import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/controls/OrbitControls.js';

const state = { system: 'mobius', jewelry: 'bracelet', seed: 4817, fidelity: 0, diameter: 68, width: 24, thickness: 3.2, material: 'PLA', sourceOverlay: false, projection: 'perspective', view: 'solid', modular: false, params: { twists: 1, waves: 3.2, chaos: 28 } };
const presets = { mobius: { title: 'Topological fidelity', copy: "The half-twist is preserved as the bracelet's continuous centerline and surface.", equation: 'x = (R + v cos(u/2) cos(u)) cos(u)', family: 'MB', params: [{ key: 'twists', label: 'HALF-TWISTS', min: 1, max: 3, step: 1, value: 1 }, { key: 'waves', label: 'RIM RIPPLE', min: 0, max: 8, step: .1, value: 3.2 }] }, lorenz: { title: 'Dynamical fidelity', copy: 'A sampled Lorenz trajectory becomes a continuous pendant path; the attractor is preserved, then thickened for printing.', equation: 'dx/dt = σ(y − x), dy/dt = x(ρ − z) − y', family: 'LZ', params: [{ key: 'chaos', label: 'RHO / CHAOS', min: 18, max: 40, step: .5, value: 28 }, { key: 'waves', label: 'PATH DENSITY', min: 1, max: 6, step: .1, value: 3.2 }] }, minimal: { title: 'Geometric interpretation', copy: 'A periodic minimal-surface field is sampled into a breathable shell. Its surface character is faithful; its cuff boundary is wearable.', equation: 'sin(x)cos(y) + sin(y)cos(z) + sin(z)cos(x) = 0', family: 'MS', params: [{ key: 'waves', label: 'UNIT CELL / PERIOD', min: 1, max: 5, step: .1, value: 2.4 }, { key: 'twists', label: 'POROSITY', min: 1, max: 5, step: .1, value: 2.5 }] } };

const ui = Object.fromEntries(['systemSelect','jewelrySelect','dynamicParams','seedInput','randomSeed','equationText','faithTitle','faithCopy','fidelitySlider','fidelityValue','diameterSlider','diameterValue','widthSlider','widthValue','thicknessSlider','thicknessValue','materialSelect','printScore','scoreBar','printStatus','warningList','dimensionReadout','meshReadout','designId','projectionToggle','sourceToggle','toggleModular','variationsButton','dnaButton','saveDna','exportStl','toast','viewport','variationGrid'].map(id => [id, document.getElementById(id)]));

const scene = new THREE.Scene(); const camera = new THREE.PerspectiveCamera(34, 1, .1, 500); camera.position.set(0, 30, 105); const orthoCamera = new THREE.OrthographicCamera(-55, 55, 55, -55, .1, 500); orthoCamera.position.copy(camera.position); let activeCamera = camera;
const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.outputColorSpace = THREE.SRGBColorSpace; ui.viewport.appendChild(renderer.domElement);
const controls = new OrbitControls(activeCamera, renderer.domElement); controls.enableDamping = true; controls.dampingFactor = .07; controls.minDistance = 45; controls.maxDistance = 170;
scene.add(new THREE.HemisphereLight(0xf7fff2, 0x9cac9a, 2.4)); const key = new THREE.DirectionalLight(0xffffff, 3); key.position.set(30, 45, 35); scene.add(key); const fill = new THREE.DirectionalLight(0xb8d9d2, 1.4); fill.position.set(-40, 0, -20); scene.add(fill);
const objectGroup = new THREE.Group(); scene.add(objectGroup); const sourceGroup = new THREE.Group(); scene.add(sourceGroup);
let currentGeometry;

function resize() { const r = ui.viewport.getBoundingClientRect(); renderer.setSize(r.width, r.height, false); camera.aspect = r.width / r.height; camera.updateProjectionMatrix(); const view = Math.max(r.width, r.height) * .34; orthoCamera.left=-view; orthoCamera.right=view; orthoCamera.top=view; orthoCamera.bottom=-view; orthoCamera.updateProjectionMatrix(); } addEventListener('resize', resize);
function makeMobius() { const geometry = new THREE.TorusGeometry(state.diameter / 2, state.width / 5.4, 18, 180); const pos = geometry.attributes.position; for (let i = 0; i < pos.count; i++) { const x = pos.getX(i), y = pos.getY(i), z = pos.getZ(i); const radial = Math.sqrt(x*x + z*z); const angle = Math.atan2(z, x); const band = y; const twist = angle * .5 * state.params.twists; pos.setY(i, band * Math.cos(twist) - radial * .045 * Math.sin(angle * state.params.waves)); pos.setZ(i, z + band * Math.sin(twist) * .72); } geometry.computeVertexNormals(); return geometry; }
function makeLorenz() { const points = []; let x = .1, y = 0, z = 0, dt = .012, rho = state.params.chaos; for (let i = 0; i < 2100; i++) { const dx = 10*(y-x), dy = x*(rho-z)-y, dz = x*y - 8/3*z; x += dx*dt; y += dy*dt; z += dz*dt; if (i > 80 && i % 2 === 0) points.push(new THREE.Vector3(x, z-25, y)); } const curve = new THREE.CatmullRomCurve3(points).getSpacedPoints(720); const radius = state.thickness/3.1; const tube = new THREE.TubeGeometry(new THREE.CatmullRomCurve3(curve), 720, radius, 8, false); tube.scale(1.05, 1.05, 1.05); return tube; }
function makeMinimal() { const geo = new THREE.TorusGeometry(state.diameter/2, state.width/4.3, 32, 180); const p=geo.attributes.position; for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i); const a=Math.atan2(z,x); const ripple=Math.sin(a*state.params.waves)*state.width*.09; p.setY(i,y+ripple*Math.cos(a*3)); p.setX(i,x+Math.cos(a*state.params.twists)*1.8); } geo.computeVertexNormals(); return geo; }
function makeSource() { const geometry = state.system === 'lorenz' ? makeLorenz() : state.system === 'minimal' ? makeMinimal() : makeMobius(); return geometry; }
function clearGroup(group) { while (group.children.length) { const child=group.children.pop(); child.geometry?.dispose(); child.material?.dispose(); } }
function renderModel() { clearGroup(objectGroup); clearGroup(sourceGroup); currentGeometry = makeSource(); const material = new THREE.MeshStandardMaterial({ color: state.material === 'TPU 95A' ? 0xe97858 : state.material === 'PETG' ? 0x237a72 : 0x27352f, roughness: state.material === 'PLA' ? .43 : .28, metalness: 0 }); const mesh = new THREE.Mesh(currentGeometry, material); mesh.rotation.x = state.system === 'lorenz' ? -.25 : 0; objectGroup.add(mesh); if (state.view === 'wire') { material.wireframe = true; } if (state.view === 'ghost') { material.transparent=true; material.opacity=.35; } if (state.sourceOverlay) { const sourceMat = new THREE.MeshBasicMaterial({ color: 0xeb7657, wireframe: true, transparent: true, opacity: .7 }); const src = new THREE.Mesh(currentGeometry.clone(), sourceMat); src.scale.setScalar(1.035); sourceGroup.add(src); } updateReadouts(); }
function updateReadouts() { const v=currentGeometry?.attributes.position.count || 0; ui.meshReadout.textContent=`MESH ${v.toLocaleString()} VERTS · ${(currentGeometry?.index?.count/3||0).toLocaleString()} FACES`; ui.dimensionReadout.textContent=`Ø ${state.diameter.toFixed(1)} MM · ${state.width.toFixed(1)} MM W`; const family=presets[state.system].family; ui.designId.textContent=`${family}-0042-${state.modular?'A/B':'A'}`; updatePrintability(); }
function updatePrintability() { let score=96 - Math.round(Math.max(0,state.thickness<2.2?12:(state.thickness<2.7?4:0)) + (state.material==='TPU 95A'?2:0) + (state.system==='lorenz'?3:0) + (state.width<15?4:0)); const warnings=[]; if(state.thickness<2.7) warnings.push('Wall approaches the 0.4 mm nozzle safety margin.'); if(state.system==='lorenz') warnings.push('Attractor path has local overhangs; orient pendant vertically.'); if(state.material==='TPU 95A') warnings.push('TPU needs slower bridging and a textured build plate.'); ui.printScore.textContent=`${score} / 100`; ui.scoreBar.style.width=`${score}%`; ui.printStatus.innerHTML=score>88?'<span>✓</span> READY FOR FDM PROTOTYPE':'<span>!</span> REVIEW PRINT WARNINGS'; ui.warningList.innerHTML=warnings.map(w=>`<div class="warning"><span>!</span>${w}</div>`).join(''); }
function renderParams() { const preset=presets[state.system]; ui.dynamicParams.innerHTML=preset.params.map(p=>`<div class="dynamic-param"><div class="param-label"><span>${p.label}</span><span id="param-${p.key}-value">${state.params[p.key]}</span></div><input data-param="${p.key}" type="range" min="${p.min}" max="${p.max}" step="${p.step}" value="${state.params[p.key]}" /></div>`).join(''); ui.faithTitle.textContent=preset.title; ui.faithCopy.textContent=preset.copy; ui.equationText.textContent=preset.equation; ui.dynamicParams.querySelectorAll('input').forEach(input=>input.addEventListener('input',()=>{state.params[input.dataset.param]=Number(input.value); document.getElementById(`param-${input.dataset.param}-value`).textContent=input.value; renderModel();})); }
function dna() { return { design_id:`${presets[state.system].family}-0042-${state.modular?'A/B':'A'}`, mathematical_system:state.system, parameters:{...state.params, mathematical_fidelity:['high','medium','experimental'][state.fidelity]}, seed:state.seed, jewelry_type:state.jewelry, dimensions_mm:{diameter:state.diameter,width:state.width,wall_thickness:state.thickness}, material:state.material, manufacturing_process:'FDM', connector_standard:state.modular?'MAG-01':'none', charm_standard:'PORT-01', mathematical_fidelity:state.fidelity===0?'faithful':state.fidelity===1?'moderated':'experimental', generated_at:new Date().toISOString() }; }
function download(name, contents, type) { const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([contents],{type})); a.download=name; a.click(); URL.revokeObjectURL(a.href); }
function exportAsciiStl() { const pos=currentGeometry.attributes.position; let out='solid orbital\n'; for(let i=0;i<pos.count-2;i+=3){const a=new THREE.Vector3().fromBufferAttribute(pos,i),b=new THREE.Vector3().fromBufferAttribute(pos,i+1),c=new THREE.Vector3().fromBufferAttribute(pos,i+2); const n=b.clone().sub(a).cross(c.clone().sub(a)).normalize(); out+=` facet normal ${n.x} ${n.y} ${n.z}\n  outer loop\n   vertex ${a.x} ${a.y} ${a.z}\n   vertex ${b.x} ${b.y} ${b.z}\n   vertex ${c.x} ${c.y} ${c.z}\n  endloop\n endfacet\n`; } return out+'endsolid orbital'; }
function toast(message) { ui.toast.textContent=message; ui.toast.classList.add('visible'); setTimeout(()=>ui.toast.classList.remove('visible'),2200); }
function generateVariations() { ui.variationGrid.innerHTML=''; for(let i=0;i<6;i++){const card=document.createElement('div'); card.className='variation'+(i===0?' selected':''); const canvas=document.createElement('canvas'); canvas.width=140;canvas.height=70; const c=canvas.getContext('2d'); c.strokeStyle=i%2?'#d8785e':'#2b7770'; c.lineWidth=2; c.beginPath(); for(let x=0;x<140;x++){const y=35+Math.sin(x*.05+(i*.7))* (8+i*1.5); if(x===0)c.moveTo(x,y);else c.lineTo(x,y)} c.stroke(); card.append(canvas); card.insertAdjacentHTML('beforeend',`<span class="variation-label">${presets[state.system].family}-00${42+i}</span><i class="variation-dot"></i>`); card.onclick=()=>{document.querySelectorAll('.variation').forEach(v=>v.classList.remove('selected'));card.classList.add('selected');state.params.waves=Number((state.params.waves+(i-2)*.3).toFixed(1));renderParams();renderModel();toast(`Loaded variation ${i+1}`)}; ui.variationGrid.append(card);} }

ui.systemSelect.onchange=e=>{state.system=e.target.value; state.params={...state.params,...Object.fromEntries(presets[state.system].params.map(p=>[p.key,p.value]))};renderParams();renderModel();generateVariations()}; ui.jewelrySelect.onchange=e=>{state.jewelry=e.target.value;renderModel()}; ui.seedInput.onchange=e=>{state.seed=Number(e.target.value)||4817;renderModel()}; ui.randomSeed.onclick=()=>{state.seed=Math.floor(1000+Math.random()*8999);ui.seedInput.value=state.seed;renderModel()}; ui.fidelitySlider.oninput=e=>{state.fidelity=Number(e.target.value);ui.fidelityValue.textContent=['HIGH','MEDIUM','EXPERIMENTAL'][state.fidelity];renderModel()}; [['diameter','diameterSlider','diameterValue',' mm'],['width','widthSlider','widthValue',' mm'],['thickness','thicknessSlider','thicknessValue',' mm']].forEach(([key,slider,value,suffix])=>ui[slider].oninput=e=>{state[key]=Number(e.target.value);ui[value].textContent=Number(e.target.value).toFixed(1)+suffix;renderModel()}); ui.materialSelect.onchange=e=>{state.material=e.target.value;renderModel()}; ui.projectionToggle.onclick=()=>{state.projection=state.projection==='perspective'?'orthographic':'perspective';activeCamera=state.projection==='perspective'?camera:orthoCamera;controls.object=activeCamera;ui.projectionToggle.firstChild.textContent=state.projection.toUpperCase()+' '; toast(`${state.projection} projection`)}; ui.sourceToggle.onclick=()=>{state.sourceOverlay=!state.sourceOverlay;ui.sourceToggle.classList.toggle('active',state.sourceOverlay);renderModel()}; ui.toggleModular.onclick=()=>{state.modular=!state.modular;ui.toggleModular.textContent=state.modular?'DISABLE':'ENABLE';renderModel()}; ui.variationsButton.onclick=()=>{generateVariations();toast('Six meaningful variations generated')}; ui.dnaButton.onclick=()=>{download('MB-0042_design_dna.json',JSON.stringify(dna(),null,2),'application/json');toast('Design DNA exported')}; ui.saveDna.onclick=()=>{download(`${presets[state.system].family}_0042_design_dna.json`,JSON.stringify(dna(),null,2),'application/json');toast('DNA saved to your downloads')}; ui.exportStl.onclick=()=>{download(`${presets[state.system].family}_0042_A.stl`,exportAsciiStl(),'model/stl');toast('STL exported for prototyping')}; document.querySelectorAll('.view-tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.view-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.view=btn.dataset.view;renderModel()});
function animate(){requestAnimationFrame(animate);controls.update();objectGroup.rotation.y+=.0015;sourceGroup.rotation.y=objectGroup.rotation.y;renderer.render(scene,activeCamera)}
renderParams(); renderModel(); generateVariations(); resize(); animate();
